apiVersion: v1
kind: Service
metadata:
  name: {{ include "dice-chart.fullname" . }}-metrics-service
  labels:
    {{- include "dice-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricService.type }}
  ports:
    - port: {{ .Values.metricService.port }}
      targetPort: {{ .Values.metricService.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "dice-chart.selectorLabels" . | nindent 4 }}
